language: android

jdk:
  # Jdk version used by your project
  - oraclejdk8

sudo: false

android:
  components:
    - platform-tools
    - tools
    # The BuildTools version used by your project
    - build-tools-24.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
      # Specify at least one system image, if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-24

  licenses:
      - android-sdk-preview-license-.+
      - android-sdk-license-.+
      - google-gdk-license-.+
    
notifications:
  email: false

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

# cache between builds
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/

install:
  # Check install section: http://docs.travis-ci.com/user/build-configuration/#install
  # If you'd like to skip the install stage entirely, set it to true and nothing will be run.
  - true

before_script:
  - chmod +x gradlew
  - echo no | android create avd --force --name test --target android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

# Build, and run tests
script: 
  # Once tests written should run the gradle task for both Mobile and Wear
  # currently only doing a normal build to test Travis config
  #- ./gradlew mobile:functionalTests
  #- ./gradlew wear:functionalTests
  # -  ./gradlew core:test --info
  - ./gradlew core:jacocoTestReport

# Codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
